import javax.swing.*;
import javax.swing.tree.*;
import javax.swing.table.*;
import javax.swing.DefaultListModel.*;
import java.io.*;
import javax.swing.JOptionPane;
import java.nio.charset.StandardCharsets;
import java.awt.*;


public class JFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameD = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jFrameH = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sifreDialog = new javax.swing.JDialog();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        randevuDialog = new javax.swing.JDialog();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tableDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jFrameD.setBackground(new java.awt.Color(235, 235, 231));
        jFrameD.setLocation(new java.awt.Point(0, 0));
        jFrameD.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrameDWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFrameDWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                jFrameDWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameDWindowOpened(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(158, 158, 131));
        jButton4.setText("Ana Menuye Don");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(158, 158, 131));
        jButton11.setText("TANI ve ILAC aktar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISIM", "SOYISIM", "CINSIYET", "YAS", "TELEFON", "TANI", "ILAC"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(158, 158, 131));
        jTable2.setSelectionBackground(new java.awt.Color(158, 158, 131));
        jScrollPane3.setViewportView(jTable2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jButton13.setBackground(new java.awt.Color(158, 158, 131));
        jButton13.setText("RAPOR KAYDET");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jMenuBar2.setBackground(new java.awt.Color(158, 158, 131));

        jMenu3.setText("Profil");
        jMenuBar2.add(jMenu3);

        jFrameD.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jFrameDLayout = new javax.swing.GroupLayout(jFrameD.getContentPane());
        jFrameD.getContentPane().setLayout(jFrameDLayout);
        jFrameDLayout.setHorizontalGroup(
            jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrameDLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(46, 46, 46))
                    .addGroup(jFrameDLayout.createSequentialGroup()
                        .addGroup(jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameDLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton13)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameDLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))))))
        );
        jFrameDLayout.setVerticalGroup(
            jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameDLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jFrameDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(37, 37, 37))
        );

        jFrameH.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameHWindowOpened(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(158, 158, 131));
        jButton3.setText("Ana Menuye Don");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hizli Randevu");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Dermatoloji ( Cildiye ) Pol.");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Taha D.");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Mehmet G.");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Kulak Burun Boğaz Hast. Pol.");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Murat F.");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Sude A.");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ortopedi ve Travmatoloji Pol.");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Serkan D.");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Neslihan K.");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ağız ve Diş Sağlığı Pol.");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Mahinur T.");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gokhan K.");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setRootVisible(false);
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jButton6.setBackground(new java.awt.Color(158, 158, 131));
        jButton6.setText("Randevu Al");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(158, 158, 131));
        jButton7.setText("Randevularimi Goster");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(158, 158, 131), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setText("TANI ve ILAC burada goruntulenecektir ");

        jMenuBar1.setBackground(new java.awt.Color(158, 158, 131));

        jMenu1.setText("Profil");
        jMenuBar1.add(jMenu1);

        jFrameH.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jFrameHLayout = new javax.swing.GroupLayout(jFrameH.getContentPane());
        jFrameH.getContentPane().setLayout(jFrameHLayout);
        jFrameHLayout.setHorizontalGroup(
            jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameHLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameHLayout.createSequentialGroup()
                        .addGroup(jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrameHLayout.createSequentialGroup()
                                .addGroup(jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrameHLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))))
        );
        jFrameHLayout.setVerticalGroup(
            jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameHLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jFrameHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameHLayout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jFrameHLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        sifreDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                sifreDialogWindowOpened(evt);
            }
        });

        jPasswordField1.setEchoChar('*');

        jLabel3.setText("SIFRE :");

        jButton5.setBackground(new java.awt.Color(158, 158, 131));
        jButton5.setText("GIRIS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sifreDialogLayout = new javax.swing.GroupLayout(sifreDialog.getContentPane());
        sifreDialog.getContentPane().setLayout(sifreDialogLayout);
        sifreDialogLayout.setHorizontalGroup(
            sifreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifreDialogLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sifreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        sifreDialogLayout.setVerticalGroup(
            sifreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreDialogLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(sifreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton5)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        sifreDialog.getAccessibleContext().setAccessibleParent(null);

        randevuDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                randevuDialogWindowOpened(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("ERKEK");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("KADIN");

        jLabel5.setText("CINSIYET");

        jLabel6.setText("ISIM");

        jLabel7.setText("SOYISIM");

        jLabel8.setText("YAS");

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));

        jButton8.setBackground(new java.awt.Color(158, 158, 131));
        jButton8.setText("ONAY");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jProgressBar1.setBackground(new java.awt.Color(158, 158, 131));
        jProgressBar1.setMaximum(5);
        jProgressBar1.setToolTipText("");
        jProgressBar1.setStringPainted(true);

        jButton9.setBackground(new java.awt.Color(158, 158, 131));
        jButton9.setText("IPTAL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel10.setText("TELEFON");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0-5##-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout randevuDialogLayout = new javax.swing.GroupLayout(randevuDialog.getContentPane());
        randevuDialog.getContentPane().setLayout(randevuDialogLayout);
        randevuDialogLayout.setHorizontalGroup(
            randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(randevuDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, randevuDialogLayout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, randevuDialogLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(randevuDialogLayout.createSequentialGroup()
                        .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(randevuDialogLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(randevuDialogLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(randevuDialogLayout.createSequentialGroup()
                                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(randevuDialogLayout.createSequentialGroup()
                                        .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(randevuDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143))))
        );
        randevuDialogLayout.setVerticalGroup(
            randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(randevuDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(randevuDialogLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(randevuDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(randevuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        tableDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                tableDialogWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "POLIKLINIK           ", "DOKTOR", "ISIM", "SOYISIM", "CINSIYET", "YAS", "TELEFON       "
            }
        ));
        jTable1.setGridColor(new java.awt.Color(158, 158, 131));
        jTable1.setSelectionBackground(new java.awt.Color(158, 158, 131));
        jScrollPane2.setViewportView(jTable1);

        jButton10.setBackground(new java.awt.Color(158, 158, 131));
        jButton10.setText("RANDEVU SIL");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableDialogLayout = new javax.swing.GroupLayout(tableDialog.getContentPane());
        tableDialog.getContentPane().setLayout(tableDialogLayout);
        tableDialogLayout.setHorizontalGroup(
            tableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableDialogLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        tableDialogLayout.setVerticalGroup(
            tableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton10)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(900, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(158, 158, 131));
        jButton1.setText("Doktor Giriş");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("HOŞ GELDINIZ !");

        jButton2.setBackground(new java.awt.Color(158, 158, 131));
        jButton2.setText("Hasta Giriş");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(158, 158, 131));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(158, 158, 131));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dermatoloji ( Cildiye ) Pol.", "Kulak Burun Boğaz Hast. Pol.", "Ortopedi ve Travmatoloji Pol.", "Ağız ve Diş Sağlığı Pol." }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel2.setText("Poliklinik :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String isim = (String)jComboBox1.getSelectedItem();
        sifreDialog.setTitle("Merhaba " + isim + "!");
        sifreDialog.setSize(400, 300);
        sifreDialog.setLocationRelativeTo(null);
        sifreDialog.setVisible(true);
        jPasswordField1.setText("");
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrameH.setBounds(0, 0, 900, 600);
        jFrameH.setLocationRelativeTo(null);
        jFrameH.setVisible(true);
        this.setVisible(false);
        
     DefaultTreeCellRenderer renderer = (DefaultTreeCellRenderer)jTree1.getCellRenderer();
     Icon closedIcon = new ImageIcon(".\\src\\icons8-polyclinic-24.png");
     Icon openIcon = new ImageIcon(".\\src\\icons8-polyclinic-24.png");
     Icon leafIcon = new ImageIcon(".\\src\\icons8-person-32.png");
     renderer.setClosedIcon(closedIcon);
     renderer.setOpenIcon(openIcon);
     renderer.setLeafIcon(leafIcon);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Color c = new Color(235,235,231);
        this.getContentPane().setBackground(c);
        
        try{
        FileInputStream fis = new FileInputStream(".\\src\\New Text Document.txt");
        InputStreamReader isr = new InputStreamReader(fis, StandardCharsets.UTF_8);
        BufferedReader br = new BufferedReader(isr);
        
        d_modeller=new DefaultComboBoxModel[4];
        
        for(int i=0; i<4; i++){
        d_modeller[i]=new DefaultComboBoxModel();
        }
        
        String line = br.readLine();
        
        
        while(line!=null){
        String[] parcala=line.split("//");
        
        System.out.println(parcala[0] + " " + parcala[1]);
        
        switch(parcala[0]){
            
        
            case "derm" :
                d_modeller[0].addElement(parcala[1]);
                break;
                
            case "kbb" :
                d_modeller[1].addElement(parcala[1]);
                break;
                
            case "ort" :
                d_modeller[2].addElement(parcala[1]);
                break;
                
            case "ads" :
                d_modeller[3].addElement(parcala[1]);
                break;
         
        }
        line=br.readLine();
        }
        
        br.close();
        
        jComboBox1.setModel(d_modeller[0]);
        }
        
        
        
        catch(NumberFormatException hata1){
        JOptionPane.showMessageDialog(null, "HATA", "Dosya formatini kontrol edin", JOptionPane.ERROR_MESSAGE);
        }
        catch(FileNotFoundException hata2){
        JOptionPane.showMessageDialog(null, "HATA", "Dosya bulunamadi", JOptionPane.ERROR_MESSAGE);
        }
        catch(IOException hata3){
        JOptionPane.showMessageDialog(null, hata3.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jFrameH.setVisible(false);
       this.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jFrameD.setVisible(false);
       this.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
       int index = jComboBox2.getSelectedIndex();
       jComboBox1.setModel(d_modeller[index]);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        String sifre = jPasswordField1.getText();
        String kontrol = jComboBox1.getSelectedItem().toString();
        
        System.out.println(kontrol);
        
        if(sifre.equals(kontrol) ){
        
        jFrameD.setBounds(0, 0, 900, 600);
        jFrameD.setLocationRelativeTo(null);
        jFrameD.setVisible(true);
        this.setVisible(false);
        sifreDialog.setVisible(false);
        }
        
        else if(sifre.equals("") ){
        JOptionPane.showMessageDialog(null, "Lutfen sifre giriniz", null, JOptionPane.ERROR_MESSAGE);
        }
        else{
        JOptionPane.showMessageDialog(null, "Sifre yanlis, tekrar deneyiniz !", null, JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        jTextField1.setText("");
        jTextField2.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextField3.setText("");
        jFormattedTextField1.setText("");
        jProgressBar1.setValue(0);
        
        
        randevuDialog.setSize(400, 400);
        randevuDialog.setLocationRelativeTo(null);
        randevuDialog.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        DefaultTreeModel tree_model = (DefaultTreeModel)jTree1.getModel();
        DefaultMutableTreeNode tree_node = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();

        String mesaj =  (tree_node.getParent().toString() + " "+ tree_node.toString() + " RANDEVU ");

        jLabel9.setText(mesaj);
    }//GEN-LAST:event_jTree1ValueChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      jProgressBar1.setValue(0);
      jProgressBar1.update(jProgressBar1.getGraphics());
      
      if( jTextField1.getText().length() != 0 ){
        
         jProgressBar1.setValue(jProgressBar1.getValue()+1);
         jProgressBar1.update(jProgressBar1.getGraphics());
         
         try{
          Thread.sleep(50); //zaman geciktirmesi yapmak icin
          }
          catch(Exception ex){
          System.out.println("Hata : " + ex.getMessage());
          }
       
      }
      else{
      return;
      }
      
      if( jTextField2.getText().length() != 0 ){
       
         jProgressBar1.setValue(jProgressBar1.getValue()+1);
         jProgressBar1.update(jProgressBar1.getGraphics());
         
         try{
          Thread.sleep(50); //zaman geciktirmesi yapmak icin
          }
          catch(Exception ex){
          System.out.println("Hata : " + ex.getMessage());
          }
       
      }
      else{
      return;
      }
      
      if( isSelected() != 0 ){
       
         jProgressBar1.setValue(jProgressBar1.getValue()+1);
         jProgressBar1.update(jProgressBar1.getGraphics());
         
         try{
          Thread.sleep(50); //zaman geciktirmesi yapmak icin
          }
          catch(Exception ex){
          System.out.println("Hata : " + ex.getMessage());
          }
       
      }
      else{
      return;
      }
      
      if( jTextField3.getText().length() != 0 ){
       
         jProgressBar1.setValue(jProgressBar1.getValue()+1);
         jProgressBar1.update(jProgressBar1.getGraphics());
         
         try{
          Thread.sleep(50); //zaman geciktirmesi yapmak icin
          }
          catch(Exception ex){
          System.out.println("Hata : " + ex.getMessage());
          }
       
      }
      else{
      return;
      }
      
      if( jFormattedTextField1.getText().equals("0-5  -   -    ") == false){
       
         jProgressBar1.setValue(jProgressBar1.getValue()+1);
         jProgressBar1.update(jProgressBar1.getGraphics());
         
         try{
          Thread.sleep(50); //zaman geciktirmesi yapmak icin
          }
          catch(Exception ex){
          System.out.println("Hata : " + ex.getMessage());
          }
       
      }
      else{
      return;
      }
      
      String randevu = "Sayin " + jTextField1.getText()+" " + jTextField2.getText() + " randevunuz olusturulmustur !";
      JOptionPane.showMessageDialog(null, randevu,null, JOptionPane.INFORMATION_MESSAGE );
      
      table_model=(DefaultTableModel)jTable1.getModel();
      String[] row_data = new String[7];
      DefaultMutableTreeNode tree_node = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
      row_data[0]=tree_node.getParent().toString();
      row_data[1]=tree_node.toString();
      row_data[2]=jTextField1.getText();
      row_data[3]=jTextField2.getText();
      
      if(isSelected()==1){
      row_data[4]="ERKEK";
      }
      else if(isSelected()==2){
      row_data[4]="KADIN";
      }
      
      row_data[5]=jTextField3.getText();
      row_data[6]=jFormattedTextField1.getText();
      
      table_model.addRow(row_data);
      jTable1.setModel(table_model);
      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        randevuDialog.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        table_model = (DefaultTableModel)jTable1.getModel();
        
        table_model.removeRow(jTable1.getSelectedRow());
        jTable1.setModel(table_model);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        tableDialog.setSize(700, 400);
        tableDialog.setLocationRelativeTo(null);
        tableDialog.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jFrameHWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameHWindowOpened
        Color c = new Color(235,235,231);
        jFrameH.getContentPane().setBackground(c);
        jPanel1.setBackground(c);
    }//GEN-LAST:event_jFrameHWindowOpened

    private void randevuDialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_randevuDialogWindowOpened
        Color c = new Color(235,235,231);
        randevuDialog.getContentPane().setBackground(c);
    }//GEN-LAST:event_randevuDialogWindowOpened

    private void tableDialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tableDialogWindowOpened
        Color c = new Color(235,235,231);
        tableDialog.getContentPane().setBackground(c);
    }//GEN-LAST:event_tableDialogWindowOpened

    private void sifreDialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_sifreDialogWindowOpened
        Color c = new Color(235,235,231);
        sifreDialog.getContentPane().setBackground(c);
    }//GEN-LAST:event_sifreDialogWindowOpened

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       if(jFileChooser1.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
       try{
       FileWriter fw=new FileWriter(jFileChooser1.getSelectedFile().getAbsolutePath(), false);
       String[] satirlar = jTextArea1.getText().split("\n");
       for(int i=0; i<satirlar.length;i++){
       fw.write(satirlar[i] + "\n");
       }
       fw.close();
       }
       
       catch(IOException hata){
       JOptionPane.showMessageDialog(null, hata.getMessage());
       }
       
       }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jFrameDWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameDWindowActivated
        Color c = new Color(235,235,231);
        jFrameD.getContentPane().setBackground(c);
        
        System.out.println("EEE");
        System.out.println("D");

        String[] rowData=new String[7];

        table_model=(DefaultTableModel)jTable1.getModel();
        table_model2=(DefaultTableModel)jTable2.getModel();

        for(int k=0; k<table_model2.getRowCount(); k++){
            table_model2.removeRow(k);
        }

        int rowNumber=jTable1.getRowCount();
        System.out.println(rowNumber + jComboBox1.getSelectedItem().toString());
        int i;
        for( i=0; i<rowNumber;i++){
            if(table_model.getValueAt(i, 1).toString().equals(jComboBox1.getSelectedItem().toString())){
                rowData[0]=table_model.getValueAt(i, 2).toString();
                rowData[1]=table_model.getValueAt(i, 3).toString();
                rowData[2]=table_model.getValueAt(i, 4).toString();
                rowData[3]=table_model.getValueAt(i, 5).toString();
                rowData[4]=table_model.getValueAt(i, 6).toString();
                rowData[5]="";
                rowData[6]="";
                table_model2.addRow(rowData);
            }

        }

        jTable2.setModel(table_model2);
    }//GEN-LAST:event_jFrameDWindowActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jFrameDWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameDWindowOpened
       
       jPanel1.removeAll();
       jPanel1.setPreferredSize(jPanel1.getSize());
        
       jPanel1.setLayout(new GridLayout(0,1));
       
       JButton tani_button = new JButton("TANI ve ILAC GORUNTULE" );
       tani_button.setForeground(Color.BLACK);
       tani_button.setName("tani_button");
       Color c = new Color(158,158,131);
       tani_button.setBackground(c);
       
       list=new JList();
       list.setForeground(Color.BLACK);
       list.setName("list");
       
       
       jPanel1.add(tani_button);
       jPanel1.add(list);
       
       
       jPanel1.validate();
       jPanel1.repaint();
       this.repaint();
       
    }//GEN-LAST:event_jFrameDWindowOpened

    private void jFrameDWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameDWindowDeactivated
       System.out.println("kontrol");
    }//GEN-LAST:event_jFrameDWindowDeactivated

    private void jFrameDWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameDWindowClosed
       System.out.println("kontrol"  );
       
       
    }//GEN-LAST:event_jFrameDWindowClosed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       System.out.println(jTable2.getModel().getValueAt(0,0).toString() + jTable2.getModel().getValueAt(0,5).toString());
       table_model2= (DefaultTableModel)jTable2.getModel();
       System.out.println(table_model2.getRowCount() );
       
       if(table_model2.getRowCount()>0){
           System.out.println("izin 1");
           int size = table_model2.getRowCount();
           int izin =0;
           
           for(int k =0;k<size;k++){
           if(table_model2.getValueAt(k, 5).toString().equals("") && table_model2.getValueAt(k, 6).toString().equals("") ){
           continue;
           }
           else{
           izin =1;
           break;
           }
           }
           
           if(izin == 1){
               System.out.println("Izin 2");
           ListModel list_model = list.getModel();
           DefaultListModel myModel = new DefaultListModel();
           String yeni;
           
           for(int i=0;i<list_model.getSize(); i++){
           myModel.addElement(list_model.getElementAt(i));
           }
           
           for(int i=0;i<size;i++){
           if(table_model2.getValueAt(i, 5).toString().equals("") && table_model2.getValueAt(i, 6).toString().equals("") ){
           continue;
           }
           else{
           yeni=table_model2.getValueAt(i, 0).toString()+ " "+table_model2.getValueAt(i, 1).toString()+" "+table_model2.getValueAt(i, 5).toString() + " " + table_model2.getValueAt(i, 6).toString();
           System.out.println(yeni);
           myModel.addElement(yeni);
           }
           
           }
           list.setModel(myModel);
           }
           
           
       }
    }//GEN-LAST:event_jButton11ActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new JFrame1().setVisible(true);
           
            }
        });
    }
    
    private int isSelected(){
    if(jRadioButton1.isSelected()){
    return 1;
    }
    if(jRadioButton2.isSelected()){
    return 2;
    }
    else{
    return 0;
    }
    }
    
    JList list;
    DefaultTableModel table_model;
    DefaultTableModel table_model2;
    public DefaultComboBoxModel[] d_modeller;
    String[] poliklinikler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFrame jFrameD;
    private javax.swing.JFrame jFrameH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTree jTree1;
    private javax.swing.JDialog randevuDialog;
    private javax.swing.JDialog sifreDialog;
    private javax.swing.JDialog tableDialog;
    // End of variables declaration//GEN-END:variables
}
